<?php

if (!defined('ABSPATH')) { exit; }

class MySecciones
{
    private $name       = 'Secciones';
    private $slug       = 'secciones';
    private $post_type  = 'secciones';

    public function __construct()
    {
    }

    public function init()
    {
        $this->init_actions();
        $this->init_filters();
    }

    public function get_name()
    {
        return $this->name;
    }

    public function get_slug()
    {
        return $this->slug;
    }

    public function get_post_type()
    {
        return $this->post_type;
    }

    public function init_actions()
    {
        add_action( 'init', [$this, 'acf_fields'] );
        add_action( 'init', [$this, 'acf_donde_esta_tips'] );
        add_action( 'init', [$this, 'acf_banco_iniciativas'] );
        add_action( 'init', [$this, 'add_post_type'] );

        add_rewrite_rule('^secciones/participacion-al-dia/publicacion/([0-9]+)/?/periodico/(.+)/?', 'index.php?/?secciones=participacion-al-dia&publicacion=$matches[1]&periodico=$matches[2]', 'top');
    }

    public function init_filters()
    {
    }

    public function load_styles()
    {
    }

    public function load_scripts()
    {
    }

    public function add_post_type()
    {
        $labels = array(
            'name'                  => $this->name,
            'singular_name'         => __('Secciones', APP_TEXTDOMAIN),
            'menu_name'             => __('Secciones', APP_TEXTDOMAIN),
            'name_admin_bar'        => __('Secciones', APP_TEXTDOMAIN),
            'archives'              => __('Secciones archive', APP_TEXTDOMAIN),
            'attributes'            => __('Secciones attributes', APP_TEXTDOMAIN),
            'parent_item_colon'     => __('Parent Sección:', APP_TEXTDOMAIN),
            'all_items'             => __('All Secciones', APP_TEXTDOMAIN),
            'add_new_item'          => __('Add new Sección', APP_TEXTDOMAIN),
            'add_new'               => __('Add New', APP_TEXTDOMAIN),
            'new_item'              => __('New Sección', APP_TEXTDOMAIN),
            'edit_item'             => __('Edit Sección', APP_TEXTDOMAIN),
            'update_item'           => __('Update Sección', APP_TEXTDOMAIN),
            'view_item'             => __('View Sección', APP_TEXTDOMAIN),
            'view_items'            => __('View Sección', APP_TEXTDOMAIN),
            'search_items'          => __('Search Sección', APP_TEXTDOMAIN),
            'not_found'             => __('No Sección found', APP_TEXTDOMAIN),
            'not_found_in_trash'    => __('No Sección found in trash', APP_TEXTDOMAIN),
            'featured_image'        => __('Featured image', APP_TEXTDOMAIN),
            'set_featured_image'    => __('Set featured image', APP_TEXTDOMAIN),
            'remove_featured_image' => __('Remove featured image', APP_TEXTDOMAIN),
            'use_featured_image'    => __('Use as featured image', APP_TEXTDOMAIN),
            'insert_into_item'      => __('Insert into Sección', APP_TEXTDOMAIN),
            'uploaded_to_this_item' => __('Upload to this Sección', APP_TEXTDOMAIN),
            'items_list'            => __('Sección list', APP_TEXTDOMAIN),
            'items_list_navigation' => __('Sección list navigation', APP_TEXTDOMAIN),
            'filter_items_list'     => __('Filter Sección list', APP_TEXTDOMAIN),
        );
        $args = array(
            'label'                 => $this->name,
            'description'           => $this->name,
            'labels'                => $labels,
            'supports'              => array('title', 'page-attributes'),
            'hierarchical'          => true,
            'public'                => true,
            'show_ui'               => true,
            'show_in_rest'          => true,
            'rest_base'             => "",
            'rest_controller_class' => "WP_REST_Posts_Controller",
            'rest_namespace'        => "wp/v2",
            'show_in_menu'          => true,
            'menu_position'         => 6,
            'menu_icon'             => 'dashicons-portfolio',
            'show_in_admin_bar'     => true,
            'show_in_nav_menus'     => true,
            'delete_with_user'      => false,
            'can_export'            => true,
            'query_var'             => true,
            'has_archive'           => false,
            'exclude_from_search'   => false,
            'publicly_queryable'    => true,
            'show_in_rest'          => false,
            'rewrite'               => array('slug' => $this->slug, 'with_front' => true),
            'capability_type'       => 'page',
            'map_meta_cap'          => true,
            'show_in_graphql' => false,
        );

        register_post_type($this->post_type, $args);
    }

    public function acf_fields()
    {
        if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array(
            'key' => 'group_638e6fd6d72fc',
            'title' => 'Secciones',
            'fields' => array(
                array(
                    'key' => 'field_638e6fe63d852',
                    'label' => 'Contenido',
                    'name' => '',
                    'type' => 'accordion',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'open' => 0,
                    'multi_expand' => 0,
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_638e6ffc3d853',
                    'label' => 'Descripción',
                    'name' => 'descripcion',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'visual',
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'delay' => 0,
                ),
                array(
                    'key' => 'field_638e702a3d854',
                    'label' => 'Contenedor Botones',
                    'name' => 'contenedor_botones',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        'layout_638e703ba16cb' => array(
                            'key' => 'layout_638e703ba16cb',
                            'name' => 'boton_izquierda',
                            'label' => 'Botón Izquierda',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_638e704c3d855',
                                    'label' => 'Titulo Botón',
                                    'name' => 'titulo_boton',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_638e70843d856',
                                    'label' => 'Página destino',
                                    'name' => 'pagina_destino',
                                    'type' => 'page_link',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array(
                                        0 => 'secciones',
                                        1 => 'cursos',
                                        2 => 'page',
                                    ),
                                    'taxonomy' => '',
                                    'allow_null' => 0,
                                    'allow_archives' => 0,
                                    'multiple' => 0,
                                ),
                                array(
                                    'key' => 'field_638e70843d857',
                                    'label' => 'Clase adicional',
                                    'name' => 'clase_adicional',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_638e70d03d85a' => array(
                            'key' => 'layout_638e70d03d85a',
                            'name' => 'boton_derecha',
                            'label' => 'Botón derecha',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_638e70d03d85b',
                                    'label' => 'Titulo Botón',
                                    'name' => 'titulo_boton',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_638e70d03d85c',
                                    'label' => 'Página destino',
                                    'name' => 'pagina_destino',
                                    'type' => 'page_link',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array(
                                        0 => 'secciones',
                                        1 => 'cursos',
                                        2 => 'page',
                                    ),
                                    'taxonomy' => '',
                                    'allow_null' => 0,
                                    'allow_archives' => 0,
                                    'multiple' => 0,
                                ),
                                array(
                                    'key' => 'field_638e70d03d85d',
                                    'label' => 'Clase adicional',
                                    'name' => 'clase_adicional',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'button_label' => 'Agregar Botón',
                    'min' => '',
                    'max' => 4,
                ),
                array(
                    'key' => 'field_638e666b64579',
                    'label' => 'Video',
                    'name' => '',
                    'type' => 'accordion',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'open' => 0,
                    'multi_expand' => 0,
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_638e1f8264575',
                    'label' => 'Agregar video?',
                    'name' => 'agregar_video',
                    'type' => 'button_group',
                    'instructions' => 'Seleccione "Si" para agregar un video',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'si' => 'Si',
                        'no' => 'No',
                    ),
                    'allow_null' => 0,
                    'default_value' => 'no',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_638e47a845851',
                    'label' => 'Insertar video de Youtube?',
                    'name' => 'insertar_video_de_youtube',
                    'type' => 'button_group',
                    'instructions' => 'Selecciona "Si" para insertar un video de Youtube',
                    'required' => 1,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_638e1f8264575',
                                'operator' => '==',
                                'value' => 'si',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'si' => 'Si',
                        'no' => 'No',
                    ),
                    'allow_null' => 0,
                    'default_value' => 'no',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_638e481345852',
                    'label' => 'Video Youtube',
                    'name' => 'video_youtube',
                    'type' => 'oembed',
                    'instructions' => 'Inserta la URL del video de Youtube',
                    'required' => 1,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_638e47a845851',
                                'operator' => '==',
                                'value' => 'si',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'width' => '',
                    'height' => '',
                ),
                array(
                    'key' => 'field_638e48d445853',
                    'label' => 'Subir video',
                    'name' => 'subir_video',
                    'type' => 'file',
                    'instructions' => 'Seleccione el video a subir',
                    'required' => 1,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_638e47a845851',
                                'operator' => '==',
                                'value' => 'no',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => 'mp4,mpeg4,mpeg,mpg',
                ),
                array(
                    'key' => 'field_638e48d556964',
                    'label' => 'Poster video',
                    'name' => 'video_poster',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_638e47a845851',
                                'operator' => '==',
                                'value' => 'no',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'uploadedTo',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_638e205b64579',
                    'label' => 'Imágenes',
                    'name' => '',
                    'type' => 'accordion',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'open' => 0,
                    'multi_expand' => 0,
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_638e1f8264686',
                    'label' => 'Agregar imágenes?',
                    'name' => 'agregar_imagenes',
                    'type' => 'button_group',
                    'instructions' => 'Seleccione "Si" para agregar imágenes',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'si' => 'Si',
                        'no' => 'No',
                    ),
                    'allow_null' => 0,
                    'default_value' => 'no',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_638e1fb264687',
                    'label' => 'Tipo de imágenes',
                    'name' => 'tipo_imagenes',
                    'type' => 'button_group',
                    'instructions' => 'Selecciona si quieres agregar una imagen estática para la sección o las imágenes de los cursos',
                    'required' => 1,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_638e1f8264686',
                                'operator' => '==',
                                'value' => 'si',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'imagen_seccion' => 'Imagen estática',
                        'imagen_cursos' => 'Imágenes cursos',
                    ),
                    'allow_null' => 0,
                    'default_value' => 'imagen_seccion',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_638e2174e264A',
                    'label' => 'Imagen Estática',
                    'name' => 'imagen_estatica',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_638e1fb264687',
                                'operator' => '==',
                                'value' => 'imagen_seccion',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'uploadedTo',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_638e2084f5b87',
                    'label' => 'Imágenes de los cursos',
                    'name' => 'imagenes',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_638e1fb264687',
                                'operator' => '==',
                                'value' => 'imagen_cursos',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => 'Agregar imagen',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_638e2174e253f',
                            'label' => 'Imagen',
                            'name' => 'imagen',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'medium',
                            'library' => 'uploadedTo',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array(
                            'key' => 'field_638e2197e2540',
                            'label' => 'Página curso',
                            'name' => 'pagina_curso',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'secciones',
                                1 => 'cursos',
                            ),
                            'taxonomy' => '',
                            'allow_null' => 1,
                            'allow_archives' => 0,
                            'multiple' => 0,
                        ),
                        array(
                            'key' => 'field_638e2197e2550',
                            'label' => 'Clase adicional',
                            'name' => 'clase_adicional',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'secciones',
                    ),
                    array(
                        'param' => 'page_type',
                        'operator' => '!=',
                        'value' => 'parent',
                    ),
                    array(
                        'param' => 'post_template',
                        'operator' => '!=',
                        'value' => 'template-donde-esta-tips.php',
                    ),
                    array(
                        'param' => 'post_template',
                        'operator' => '!=',
                        'value' => 'template-banco-iniciativas.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
            'active' => true,
            'description' => '',
        ));

        endif;
    }

    public function acf_donde_esta_tips()
    {
        if( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array(
                'key' => 'group_63e505611d173',
                'title' => 'Bloque diálogos ciudadanos y agendas',
                'fields' => array(
                    array(
                        'key' => 'field_63e50561d0b43',
                        'label' => 'Contenido',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_63e50561d0b93',
                        'label' => 'Descripción fija',
                        'name' => 'descripcion_fija',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_63e50cbc99b93',
                        'label' => 'Link biblioteca Tips',
                        'name' => 'link_biblioteca_tips',
                        'type' => 'page_link',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'post_type' => array(
                            0 => 'secciones',
                        ),
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'allow_archives' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_63e50cdb99b94',
                        'label' => 'Link contacta a tu gestor',
                        'name' => 'link_contacta_a_tu_gestor',
                        'type' => 'page_link',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'post_type' => array(
                            0 => 'secciones',
                        ),
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'allow_archives' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_63e520b30a23a',
                        'label' => 'Videos y agendas',
                        'name' => 'videos_y_agendas',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'collapsed' => 'field_63e520c70a23b',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_63e520c70a23b',
                                'label' => 'Localidad',
                                'name' => 'localidad',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'taxonomy' => 'localidades',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'add_term' => 1,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_63e520fe0a23c',
                                'label' => 'Video',
                                'name' => 'video',
                                'type' => 'audio_video_player',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'general_type' => 'video',
                                'mime_types' => '',
                                'return_format' => 'url',
                                'library' => 'all',
                                'min_size' => '',
                                'max_size' => '',
                            ),

                            array(
                                'key' => 'field_63e520fe1b34d',
                                'label' => 'Poster video',
                                'name' => 'video_poster',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                                'library' => 'uploadedTo',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),

                            array(
                                'key' => 'field_63e521210a23d',
                                'label' => 'Agenda',
                                'name' => 'agenda',
                                'type' => 'file',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'return_format' => 'url',
                                'library' => 'all',
                                'min_size' => '',
                                'max_size' => '',
                                'mime_types' => 'pdf',
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'secciones',
                        ),
                        array(
                            'param' => 'page_type',
                            'operator' => '!=',
                            'value' => 'top_level',
                        ),
                        array(
                            'param' => 'post_template',
                            'operator' => '==',
                            'value' => 'template-donde-esta-tips.php',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

            acf_add_local_field_group(array(
                'key' => 'group_63e93e1c5c6d0',
                'title' => 'Bloque Laboratorio TIPS',
                'fields' => array(
                    array(
                        'key' => 'field_63e93e1cc648b',
                        'label' => 'Contenido',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_63e93e1cc64d4',
                        'label' => 'Titulo',
                        'name' => 'titulo_laboratorio_tips',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_63ed31ec56b9b',
                        'label' => 'Video',
                        'name' => 'video_laboratirio_tips',
                        'type' => 'audio_video_player',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'general_type' => 'video',
                        'mime_types' => '',
                        'return_format' => 'url',
                        'library' => 'all',
                        'min_size' => '',
                        'max_size' => '',
                    ),
                    array(
                        'key' => 'field_63ed31ec67c0c',
                        'label' => 'Poster video',
                        'name' => 'poster_video_laboratirio_tips',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'uploadedTo',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_63ed30ee56b97',
                        'label' => 'Elementos carrusel',
                        'name' => 'elementos_carrusel_laboratorio_tips',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'collapsed' => 'field_63ed310456b98',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Agregar elemento',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_63ed310456b98',
                                'label' => 'Localidad',
                                'name' => 'localidad',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'taxonomy' => 'localidades',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'add_term' => 0,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_63ed319e56b99',
                                'label' => 'Multimedia',
                                'name' => 'multimedia',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'collapsed' => 'field_63ed31d356b9a',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'block',
                                'button_label' => 'Agregar elemento',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_63ed31d356b9a',
                                        'label' => 'Imagen',
                                        'name' => 'miniatura',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'return_format' => 'array',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'secciones',
                        ),
                        array(
                            'param' => 'page_type',
                            'operator' => '!=',
                            'value' => 'top_level',
                        ),
                        array(
                            'param' => 'post_template',
                            'operator' => '==',
                            'value' => 'template-donde-esta-tips.php',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

            acf_add_local_field_group(array(
                'key' => 'group_63e903670995e',
                'title' => 'Bloque Oficina de participación',
                'fields' => array(
                    array(
                        'key' => 'field_63e90367c1d2f',
                        'label' => 'Contenido',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_63e918aa40dc4',
                        'label' => 'Botón conoce al equipo de participación',
                        'name' => 'boton_conoce_al_equipo_de_participacion',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'post_type' => array(
                            0 => 'secciones',
                        ),
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'return_format' => 'id',
                        'ui' => 1,
                    ),
                    array(
                        'key' => 'field_63e90367c1dd5',
                        'label' => 'Subredes',
                        'name' => 'subredes',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'collapsed' => 'field_63e9050473bd4',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Agregar SUBRED',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_63e9050473bd4',
                                'label' => 'Titulo',
                                'name' => 'titulo',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_63e9052d73bd5',
                                'label' => 'Imagen SUBREDES',
                                'name' => 'imagen_subredes',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'field_63e9036bc8d48',
                                'label' => 'Localidad',
                                'name' => 'localidad',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'taxonomy' => 'localidades',
                                'field_type' => 'multi_select',
                                'allow_null' => 0,
                                'add_term' => 1,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_63e9036bc8dec',
                                'label' => 'Descripción',
                                'name' => 'descripcion',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'secciones',
                        ),
                        array(
                            'param' => 'page_type',
                            'operator' => '!=',
                            'value' => 'top_level',
                        ),
                        array(
                            'param' => 'post_template',
                            'operator' => '==',
                            'value' => 'template-donde-esta-tips.php',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

            acf_add_local_field_group(array(
                'key' => 'group_63e652ff118c3',
                'title' => 'Bloque Proyectos de Inversión local',
                'fields' => array(
                    array(
                        'key' => 'field_63e652ffc20dd',
                        'label' => 'Contenido',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_63e65336285e6',
                        'label' => 'Titulo',
                        'name' => 'titulo_proyectos_de_inversion_local',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_63e652ffc2206',
                        'label' => 'Elementos carrusel',
                        'name' => 'elementos_carrusel',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'collapsed' => 'field_63e654da285e7',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Agregar elemento',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_63e65305512c0',
                                'label' => 'Localidad',
                                'name' => 'localidad',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'taxonomy' => 'localidades',
                                'field_type' => 'multi_select',
                                'allow_null' => 0,
                                'add_term' => 1,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_63e654da285e7',
                                'label' => 'Titulo',
                                'name' => 'titulo',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_63e654e2285e8',
                                'label' => 'Descripción',
                                'name' => 'descripcion',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_63e68275a4bec',
                                'label' => 'Miniatura',
                                'name' => 'miniatura',
                                'type' => 'image',
                                'instructions' => 'Es la imagen que aparece en el carrusel, la imagen debe ser de 700x350',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => 700,
                                'min_height' => 350,
                                'min_size' => '',
                                'max_width' => 700,
                                'max_height' => 350,
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'field_63e6530551313',
                                'label' => 'Video',
                                'name' => 'video',
                                'type' => 'audio_video_player',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'relevanssi_exclude' => 0,
                                'general_type' => 'video',
                                'mime_types' => '',
                                'return_format' => 'url',
                                'library' => 'all',
                                'min_size' => '',
                                'max_size' => '',
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'secciones',
                        ),
                        array(
                            'param' => 'page_type',
                            'operator' => '!=',
                            'value' => 'top_level',
                        ),
                        array(
                            'param' => 'post_template',
                            'operator' => '==',
                            'value' => 'template-donde-esta-tips.php',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

            acf_add_local_field_group(array(
                'key' => 'group_63e407185ab2e',
                'title' => 'Secciones Donde esta TIPS',
                'fields' => array(
                    array(
                        'key' => 'field_63e40f3c23e73',
                        'label' => 'Contenido',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_63e40f7f23e74',
                        'label' => 'Descripción',
                        'name' => 'descripcion',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_63e40f9c23e75',
                        'label' => 'Contenedor Botones',
                        'name' => 'contenedor_botones',
                        'type' => 'flexible_content',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'layouts' => array(
                            'layout_63e40fa938c9a' => array(
                                'key' => 'layout_63e40fa938c9a',
                                'name' => 'boton_izquierda',
                                'label' => 'Botón Izquierda',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_63e40fc323e76',
                                        'label' => 'Titulo Botón',
                                        'name' => 'titulo_boton',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_63e40fd223e77',
                                        'label' => 'Página destino',
                                        'name' => 'pagina_destino',
                                        'type' => 'page_link',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'post_type' => array(
                                            0 => 'secciones',
                                            1 => 'cursos',
                                            2 => 'page',
                                        ),
                                        'taxonomy' => '',
                                        'allow_null' => 0,
                                        'allow_archives' => 0,
                                        'multiple' => 0,
                                    ),
                                    array(
                                        'key' => 'field_63e4100d23e78',
                                        'label' => 'Clase adicional',
                                        'name' => 'clase_adicional',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            'layout_63e4102f23e79' => array(
                                'key' => 'layout_63e4102f23e79',
                                'name' => 'boton_derecha',
                                'label' => 'Botón derecha',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_63e4102f23e7a',
                                        'label' => 'Titulo Botón',
                                        'name' => 'titulo_boton',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_63e4102f23e7b',
                                        'label' => 'Página destino',
                                        'name' => 'pagina_destino',
                                        'type' => 'page_link',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'post_type' => array(
                                            0 => 'secciones',
                                            1 => 'cursos',
                                            2 => 'page',
                                        ),
                                        'taxonomy' => '',
                                        'allow_null' => 0,
                                        'allow_archives' => 0,
                                        'multiple' => 0,
                                    ),
                                    array(
                                        'key' => 'field_63e4102f23e7c',
                                        'label' => 'Clase adicional',
                                        'name' => 'clase_adicional',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                        'button_label' => 'Agregar Botón',
                        'min' => '',
                        'max' => 4,
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'secciones',
                        ),
                        array(
                            'param' => 'page_type',
                            'operator' => '!=',
                            'value' => 'top_level',
                        ),
                        array(
                            'param' => 'post_template',
                            'operator' => '==',
                            'value' => 'template-donde-esta-tips.php',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

        endif;
    }

    public function acf_banco_iniciativas()
    {
        if( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array(
                'key' => 'group_63e407185bc3f',
                'title' => 'Secciones Banco de Iniciativas',
                'fields' => array(
                    array(
                        'key' => 'field_63e40f3c24f84',
                        'label' => 'Contenido',
                        'name' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_63e40f7f24f85',
                        'label' => 'Descripción',
                        'name' => 'descripcion',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_63e40f9c24f86',
                        'label' => 'Contenedor Botones',
                        'name' => 'contenedor_botones',
                        'type' => 'flexible_content',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'relevanssi_exclude' => 0,
                        'layouts' => array(
                            'layout_63e40fa939d0b' => array(
                                'key' => 'layout_63e40fa939d0b',
                                'name' => 'boton_izquierda',
                                'label' => 'Botón Izquierda',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_63e40fc324f87',
                                        'label' => 'Titulo Botón',
                                        'name' => 'titulo_boton',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_63e40fd224f88',
                                        'label' => 'Página destino',
                                        'name' => 'pagina_destino',
                                        'type' => 'page_link',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'post_type' => array(
                                            0 => 'secciones',
                                            1 => 'cursos',
                                            2 => 'page',
                                        ),
                                        'taxonomy' => '',
                                        'allow_null' => 0,
                                        'allow_archives' => 0,
                                        'multiple' => 0,
                                    ),
                                    array(
                                        'key' => 'field_63e4100d24f89',
                                        'label' => 'Clase adicional',
                                        'name' => 'clase_adicional',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            'layout_63e4102f24f90' => array(
                                'key' => 'layout_63e4102f23e79',
                                'name' => 'boton_derecha',
                                'label' => 'Botón derecha',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_63e4102f24f8b',
                                        'label' => 'Titulo Botón',
                                        'name' => 'titulo_boton',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_63e4102f24f8c',
                                        'label' => 'Página destino',
                                        'name' => 'pagina_destino',
                                        'type' => 'page_link',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'post_type' => array(
                                            0 => 'secciones',
                                            1 => 'cursos',
                                            2 => 'page',
                                        ),
                                        'taxonomy' => '',
                                        'allow_null' => 0,
                                        'allow_archives' => 0,
                                        'multiple' => 0,
                                    ),
                                    array(
                                        'key' => 'field_63e4102f24f8d',
                                        'label' => 'Clase adicional',
                                        'name' => 'clase_adicional',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'relevanssi_exclude' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                        'button_label' => 'Agregar Botón',
                        'min' => '',
                        'max' => 4,
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'secciones',
                        ),
                        array(
                            'param' => 'page_type',
                            'operator' => '!=',
                            'value' => 'top_level',
                        ),
                        array(
                            'param' => 'post_template',
                            'operator' => '==',
                            'value' => 'template-banco-iniciativas.php',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

        endif;
    }
}